name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write         # per OIDC
      contents: read
    steps:
      # ↳ Clona il repo
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # ↳ (facoltativo) installa client OIDC per uso interno
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      # ↳ Ottieni il JWT (Id Token) dal workload identity
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const core = require('@actions/core');
            return await core.getIDToken();
          result-encoding: string

      # ↳ Build & Deploy su Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_WATER_0218F8B03 }}
          action: "upload"

          # --- Percorsi repo ---
          app_location: "frontend"   # sorgente React
          api_location: "api"        # cartella Functions (upload)
          output_location: "build"   # directory di build CRA

          github_id_token: ${{ steps.idtoken.outputs.result }}

  # ----- Chiude la PR se viene chiusa su GitHub -----
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
